config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  # devise_scope :user do
  #   # Redirects signing out users back to sign-in
  #   get "users", to: "devise/sessions#new"
  # end
  devise_for :users
  
  resources :users, only: %i[show] do
    resources :invitations, only: [:index]
  end

  resources :events do
    resources :invitations, only: %i[create destroy]
    get 'search', to: 'invitations#search', as: 'invitations_search'
  end
  
  resources :invitations, only: %i[update]
end

app/views/layouts/nav/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-3 nav-color">
  <div class="container w-sm-50 w-100">
    <%= link_to 'Private Events', root_path, class: 'navbar-brand fw-bold mr-5' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse ml-5" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Create Event", new_event_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav">
        <%= render 'layouts/nav/notifications' %>
        <%= render 'layouts/nav/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/nav/_notifications.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle position-relative" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-bell-fill" style="font-size: 20px"></i>
      <%= notification_count %>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <li><%= link_to 'Invitations', user_invitations_path(current_user), class: 'dropdown-item' %></li>
      <hr class="dropdown-divider">
      <% @unread_notifications.each do |invite| %>
        <li><%= link_to "Event: #{invite.event.title.titleize} - Host: #{invite.event.host.username}", "#{user_invitations_path(current_user)}##{dom_id invite.event}", class: 'dropdown-item'%></li>
      <% end %>
    </ul>
  </li>
<% end %>

app/views/layouts/nav/_session_manager.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <%= current_user.username %>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <li><%= link_to "Settings", edit_user_registration_path, class:"dropdown-item" %></li>
      <hr class="dropdown-divider">
      <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
    </ul>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Login", new_user_session_path, class:'nav-link'%>
  </li>
<% end %>