config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  # devise_scope :user do
  #   # Redirects signing out users back to sign-in
  #   get "users", to: "devise/sessions#new"
  # end
  devise_for :users
  
  resources :users, only: %i[show] do
    resources :invitations, only: [:index]
  end

  resources :events do
    resources :invitations, only: %i[create destroy]
    get 'search', to: 'invitations#search', as: 'invitations_search'
  end
  
  resources :invitations, only: %i[update]
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :bigint           not null, primary key
#  title       :string           not null
#  description :string
#  location    :string           not null
#  start_date  :date             not null
#  end_date    :date             not null
#  start_time  :time             not null
#  end_time    :time             not null
#  creator_id  :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  private     :boolean          default(FALSE)
#
class Event < ApplicationRecord
  belongs_to :host, foreign_key: :creator_id, class_name: 'User'
  has_many :invitations, dependent: :destroy
  has_many :attendees, through: :invitations, source: :attendee

  validates :title, :location, :start_date, :end_date, :start_time, :end_time, presence: true

  scope :past, -> { includes(:host).where('end_date < ?', Date.today).order(end_date: :desc) }
  scope :future, -> { includes(:host).where('end_date > ?', Date.today).order(:end_date) }
  scope :public_events, -> { where(private: false) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :authenticate_host, only: %i[edit update]
  before_action :set_event, only: %i[show edit update destroy]
  
  def index
    @events = Event.all.includes(:host)
  end

  def show
    @invites = @event.invitations.includes(:attendee).order(:status)
    invite = Invitation.find_by(event: @event, attendee: current_user) # find or create by?
    @invite = invite.nil? ? Invitation.new : invite
  end

  def new
    @event = Event.new
    @users = User.where.not(id: current_user.id)
  end

  def create
    @event = current_user.created_events.build(event_params)
    @event.attendees << current_user
    @event.invitations.last.status = 'accepted'

    if @event.save
      redirect_to event_path(@event), notice: "Event created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event.invitations.build
    @users = User.all
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event), notice: "Event updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: "Event removed!"
  end

    private
    
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(
        :title,
        :description,
        :location,
        :start_date,
        :end_date,
        :start_time,
        :end_time,
        :private
      )
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def formatted_date(date, time)
    date.strftime("%a. %b %-d %Y") + time.strftime(" at %l:%M %P")
  end

  def time_to_event(start_date, end_date)
    current = Time.zone.now
    if start_date > current
      "Starts in: #{distance_of_time_in_words(current, start_date)}"
    elsif current.between?(start_date, end_date)
      "Event is currently live!"
    else
      "Event ended: #{time_ago_in_words(start_date)} ago"
    end
  end

  def invitation_status(status)
    case status
    when 'unconfirmed'
      content_tag :div, class: "badge bg-warning text-black col-auto" do 
        'Awaiting'
      end
    when 'accepted'
      content_tag :div, class: "badge bg-success text-light col-auto" do
        'Joined'
      end
    when 'declined'
      content_tag :div, class: "badge bg-danger text-white col-auto" do 
        'Declined'
      end
    end
  end
end

app/views/events/_event.html.erb
<div class="card mb-3 list-group list-group-item-action">
  <div class="container card-body">
    <div class="row align-items-center">
    <%= link_to event.title.titleize, event_url(event), class: 'h5 card-title col-auto me-auto' %>
      <small class="col-auto card-subtitle text-muted"><%= time_to_event(event.start_date) %></small>
    </div>
    
    <hr class="my-1">
    
    <div class="row justify-content-between">
      <div class="col">
        <p class="mt-2 card-text">
          <i class="bi bi-person-circle me-1"></i>
          <span class='fw-bold'>Host: </span><%= link_to event.host.username, user_path(event.host) %>
        </p>
        <p class="mt-2 card-text">
          <i class="bi bi-geo-alt me-1"></i>
          <span class='fw-bold'>Location: </span><%= event.location %>
        </p>
        <p class="mt-2 card-text">
          <i class="bi bi-calendar-heart me-1"></i>
          <span class='fw-bold'>Start Time: </span>
          <%= formatted_date(event.start_date, event.start_time) %>
        </p>
        <p class="mt-2 card-text">
          <i class="bi bi-calendar-x"></i>
          <span class='fw-bold'>End Time: </span>
          <%= formatted_date(event.end_date, event.end_time) %>
        </p>
      </div>
      <div class="col-5 d-flex justify-content-end align-items-end gap-2">

      <% if params[:controller] == 'invitations' %>
          <%= render 'invitations/invitation_btns', invite: invite %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_event_btns.html.erb
<% if current_user == @event.host %>
  <%= link_to 'Edit Event', edit_event_path, class: "btn btn-primary" %>
  <%= button_to 'Delete Event', event_path, method: :delete, data: { turbo_confirm: "Delete Event?" }, class: "btn btn-primary" %>
<% elsif @event.attendees.include?(current_user) %>
  <%= button_to 'Leave Event', event_invitation_path(@event, @invite), method: :delete, data: { turbo_confirm: "Leave Event?" }, class: 'btn btn-primary' %>
<% else %>
  <%= form_with model: @invite, url: event_invitations_path(@event) do |f| %>
    <%= f.hidden_field :event_id, value: @event.id %>
    <%= f.hidden_field :attendee_id, value: current_user.id %>
    <%= f.hidden_field :status, value: 'accepted' %>
    <%= f.submit "Join Event", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: event do |f| %>
  <% if event.errors.any? %>
    <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
    <% event.errors.each do |error| %>
    <ul>
      <li><%= error.full_message %></li>
    </ul>
    <% end %>
  <% end %>

  <div class="field">
    <%= f.label :title, "Event Name" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.time_field :start_time, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_field :end_date, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.time_field :end_time, class: 'form-control' %>
  </div>

  <div class="field form-check">
    <%= f.label :private, 'Private Event' %>
    <%= f.check_box :private, class:"form-check-input" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Private Events', root_path, class: 'navbar-brand' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "#{current_user.username}'s Events (WIP)", root_path, class: 'btn btn-outline-dark btn-sm' %>
          </li>
        <% end %>
      </ul>

      <ul class="nav justify-content-end gap-1">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Create Event", new_event_path, class: 'btn btn-outline-dark btn-sm' %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile: #{current_user.username}", user_path(current_user), class: 'btn btn-outline-dark btn-sm'%>
          </li>
          <li class="nav-item">
            <%= link_to "Settings", edit_user_registration_path, class: 'btn btn-outline-dark btn-sm'%>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-outline-dark btn-sm'%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in / Sign up", new_user_session_path, class: 'btn btn-outline-dark btn-sm'%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<% if current_user %>
  <div class="card">
    <ul class="mt-3 nav nav-tabs" id="nav-tab" role="tablist">
      <li class="ms-3 nav-item" role="presentation">
        <button class="nav-link active" id="future-events-tab" data-bs-toggle="tab" data-bs-target="#future-events-tab-pane" type="button" role="tab" aria-controls="future-events-tab-pane" aria-selected="true">Upcoming Events</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="my-events-tab" data-bs-toggle="tab" data-bs-target="#my-events-tab-pane" type="button" role="tab" aria-controls="my-events-tab-pane" aria-selected="false">My Events</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="past-events-tab" data-bs-toggle="tab" data-bs-target="#past-events-tab-pane" type="button" role="tab" aria-controls="past-events-tab-pane" aria-selected="false">Past Events</button>
      </li>
    </ul>
    <div class="tab-content p-3" id="nav-tabContent">
      <div class="tab-pane fade show active" id="future-events-tab-pane" role="tabpanel" aria-labelledby="future-events-tab" tabindex="0">
        <%= render 'layouts/shared/events_list', events: @events.future.public_events %>
      </div>
      <div class="tab-pane fade" id="my-events-tab-pane" role="tabpanel" aria-labelledby="my-events-tab" tabindex="0">
        <%= render 'layouts/shared/events_list', events: current_user.created_events %>
      </div>
      <div class="tab-pane fade" id="past-events-tab-pane" role="tabpanel" aria-labelledby="past-events-tab" tabindex="0">
        <%= render 'layouts/shared/events_list', events: @events.past.public_events %>
      </div>
    </div>
  </div>
<% else %>
  <div class="m-5">
    <%= render 'layouts/shared/events_list', events: @events %>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-between align-items-center">
    <h1 class="col-md-auto display-6 fw-bold"><%= @event.title.titleize %></h1>
    <div class="col-md-auto gap-1 d-flex">
      <%= render 'events/event_btns' if current_user %>
    </div>
  </div>
  
  <div class="container card mb-3">
    <div class="row">
      <div class="col-4 card-body">
        <p class="card-text">
          <i class="bi bi-person-circle me-1"></i>
          <span class="fw-bold">Host:</span>
          <%= link_to @event.host.username, user_path(@event.host), style: "text-decoration: none" %>
        </p>
        <p class="card-text">
          <i class="bi bi-geo-alt me-1"></i>
          <span class="fw-bold">Location:</span>
          <span class="text-muted"><%= @event.location.titleize %></span>
        </p>
        <p class="card-text">
          <i class="bi bi-calendar-heart me-1"></i>
          <span class="fw-bold">Start Time:</span>
          <span class="text-muted"><%= formatted_date(@event.start_date, @event.start_time) %></span>
        </p>
        <p class="card-text">
          <i class="bi bi-calendar-x"></i>
          <span class="fw-bold">End Time:</span>
          <span class="text-muted"><%= formatted_date(@event.end_date, @event.end_time) %></span>
        </p>
        <% if @event.private %>
          <p class="card-text">
            <i class="bi bi-lock"></i>
            <span class="fw-bold">*Private Event*</span>
          </p>
        <% end %>
      </div>

      <div class="col-7 card-body">
        <p class="card-text mb-1">
          <i class="bi bi-card-text"></i>
          <span class="fw-bold">Event Details:</span>
          <p class="lead"><%= @event.description %></p>
        </p>
      </div>
    </div>
  </div>
  
  <% if current_user %>
    <div class="container d-flex justify-content-between align-items-center">
      <p class="fs-5">Guests</p>
      <% if current_user == @event.host %>
        <%= link_to 'Invite Guests', event_invitations_search_path(@event), class: 'btn btn-primary btn-sm' %>
      <% end %>
    </div>

    <div class="container list-group">
      <% if @invites.empty? %>
        <p class="text-center text-muted">No one has attended this event yet!</p>
      <% else %>
        <% @invites.each do |invite| %>
          <div class="list-group-item">
            <div class="row align-items-center">
              <i class="col-auto bi bi-person-circle pe-0"></i>
              <div class="col-auto me-auto"><%= link_to invite.attendee.username, user_path(invite.attendee), style: "text-decoration: none" %></div>
              <%= invitation_status(invite.status) %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>